export const SITE_CONFIG = {
  name: 'Plumeria Vacation Rentals',
  legalName: 'Plumeria Vacation Rentals LLC',
  tagline: 'Stay at Waikiki Banyan. Experience Waikiki with Plumeria Vacation Rentals.',
  shortDescription: 'Welcoming, boutique short-term vacation rentals at Waikiki Banyan, Honolulu, Hawaiʻi.',
  email: 'plumeria.vacationrentals808@gmail.com',
  phone: '(808) 671-9191',
  phoneRaw: '+18086719191',
  address: {
    building: 'Waikiki Banyan',
    street: '201 ʻOhua Avenue',
    city: 'Honolulu',
    state: 'HI',
    zip: '96815',
    island: 'Oʻahu',
    stateLong: 'Hawaiʻi',
  },
  geo: {
    lat: 21.2753,
    lng: -157.8227,
  },
  colors: {
    pacificNavy: '#0D274D',
    waikikiOcean: '#186A9E',
    tropicalAqua: '#4BB8C7',
    sunsetCoral: '#F78D74',
    hawaiianGold: '#F5B82E',
    plumeriaBlush: '#FFF0F2',
    warmSand: '#FAF9F5',
    surfWood: '#E6C89C',
  },
  navItems: [
    { label: 'Home', href: '/' },
    { label: 'Our Rentals', href: '/rentals' },
    { label: 'Waikiki Banyan', href: '/waikiki-banyan' },
    { label: 'Explore Waikiki', href: '/explore' },
    { label: 'About', href: '/about' },
    { label: 'FAQ', href: '/faq' },
    { label: 'Contact', href: '/contact' },
  ],
  brandValues: [
    {
      symbol: 'plumeria',
      title: 'Plumeria',
      subtitle: 'A warm island welcome',
      description: 'Hospitality, comfort, and thoughtful vacation stays designed to make you feel right at home in paradise.',
    },
    {
      symbol: 'ocean',
      title: 'Ocean',
      subtitle: 'Waikiki is calling',
      description: 'Steps away from the warm Pacific swells, soft sandy beaches, and golden ocean breezes.',
    },
    {
      symbol: 'rainbow',
      title: 'Rainbow',
      subtitle: 'Made in the colors of Hawaiʻi',
      description: 'A tribute to the vibrant island skies, afternoon mist, and the rich spirit of Aloha.',
    },
    {
      symbol: 'surf',
      title: 'Surf',
      subtitle: 'Live the Waikiki lifestyle',
      description: 'Celebrate Waikiki’s historic wave-riding heritage with your board under arm and sand between your toes.',
    },
  ],
};
