export const SITE_CONFIG = {
  name: 'Plumeria Vacation Rentals',
  legalName: 'Plumeria Vacation Rentals LLC',
  tagline: 'Stay at Waikiki Banyan. Experience Waikiki with Plumeria Vacation Rentals.',
  shortDescription: 'Welcoming, boutique short-term vacation rentals at Waikiki Banyan, Honolulu, Hawaiʻi.',
  email: 'plumeria.vacationrentals808@gmail.com',
  phone: '(808) 671-9191',
  phoneRaw: '+18086719191',
  address: {
    building: 'Waikiki Banyan',
    street: '201 ʻOhua Avenue',
    city: 'Honolulu',
    state: 'HI',
    zip: '96815',
    island: 'Oʻahu',
    stateLong: 'Hawaiʻi',
  },
  geo: {
    lat: 21.2753,
    lng: -157.8227,
  },
  colors: {
    ivory: '#F9F7F2',
    sand: '#E8DCC6',
    plumeriaCream: '#F6E7A7',
    sageGreen: '#8CA58A',
    oceanBlue: '#7FB6D9',
    deepPine: '#1A3B34',
    warmGold: '#C59B4B',
    // Compatibility aliases
    pacificNavy: '#1A3B34',
    waikikiOcean: '#2A5D52',
    tropicalAqua: '#7FB6D9',
    sunsetCoral: '#C59B4B',
    hawaiianGold: '#F6E7A7',
    plumeriaBlush: '#F9F7F2',
    warmSand: '#F9F7F2',
    surfWood: '#E8DCC6',
  },
  navItems: [
    { label: 'Home', href: '/' },
    { label: 'Our Rentals', href: '/rentals' },
    { label: 'Waikiki Banyan', href: '/waikiki-banyan' },
    { label: 'Explore Waikiki', href: '/explore' },
    { label: 'House Rules', href: '/rules' },
    { label: 'FAQ', href: '/faq' },
    { label: 'Contact', href: '/contact' },
  ],
  brandValues: [
    {
      symbol: 'plumeria',
      title: 'Plumeria Flower',
      subtitle: 'A warm island welcome',
      description: 'Hospitality, comfort, and thoughtful vacation stays designed to make you feel right at home in paradise.',
    },
    {
      symbol: 'ocean',
      title: 'Coastal Waves',
      subtitle: 'Waikiki is calling',
      description: 'Steps away from the warm Pacific swells, soft sandy beaches, and golden ocean breezes.',
    },
    {
      symbol: 'palm',
      title: 'Island Palm',
      subtitle: 'Tropical living & tranquility',
      description: 'A tribute to breezy shade, relaxing afternoons, and the timeless beauty of Honolulu.',
    },
    {
      symbol: 'villa',
      title: 'Waikiki Retreat',
      subtitle: 'Your home in paradise',
      description: 'Handcrafted comforts, modern amenities, and welcoming spaces for memorable Hawaiian vacations.',
    },
  ],
};
